// Comprehensive exercise database. Each: { id, name, category, equipment }
// Categories: chest, back, shoulders, biceps, triceps, legs, glutes, core, cardio, mobility, fullbody

export const CATEGORIES = [
  { key: 'chest',     label: 'Chest',     emoji: '💪' },
  { key: 'back',      label: 'Back',      emoji: '🪢' },
  { key: 'shoulders', label: 'Shoulders', emoji: '🤾' },
  { key: 'biceps',    label: 'Biceps',    emoji: '💪' },
  { key: 'triceps',   label: 'Triceps',   emoji: '🦾' },
  { key: 'legs',      label: 'Legs',      emoji: '🦵' },
  { key: 'glutes',    label: 'Glutes',    emoji: '🍑' },
  { key: 'core',      label: 'Core',      emoji: '🦴' },
  { key: 'cardio',    label: 'Cardio',    emoji: '🏃' },
  { key: 'mobility',  label: 'Mobility',  emoji: '🧘' },
  { key: 'fullbody',  label: 'Full Body', emoji: '🔥' },
];

const ex = (id, name, category, equipment = 'none') => ({ id, name, category, equipment });

export const EXERCISES = [
  // === CHEST ===
  ex('bench_press_barbell',       'Barbell Bench Press',          'chest', 'barbell'),
  ex('bench_press_dumbbell',      'Dumbbell Bench Press',         'chest', 'dumbbell'),
  ex('incline_bench_barbell',     'Incline Barbell Bench',        'chest', 'barbell'),
  ex('incline_bench_dumbbell',    'Incline Dumbbell Bench',       'chest', 'dumbbell'),
  ex('decline_bench_barbell',     'Decline Barbell Bench',        'chest', 'barbell'),
  ex('chest_fly_dumbbell',        'Dumbbell Chest Fly',           'chest', 'dumbbell'),
  ex('chest_fly_cable',           'Cable Chest Fly',              'chest', 'cable'),
  ex('chest_fly_machine',         'Pec Deck / Machine Fly',       'chest', 'machine'),
  ex('cable_crossover_high',      'Cable Crossover (High to Low)','chest', 'cable'),
  ex('cable_crossover_low',       'Cable Crossover (Low to High)','chest', 'cable'),
  ex('pushup',                    'Pushup',                       'chest', 'none'),
  ex('pushup_diamond',            'Diamond Pushup',               'chest', 'none'),
  ex('pushup_decline',            'Decline Pushup',               'chest', 'none'),
  ex('pushup_archer',             'Archer Pushup',                'chest', 'none'),
  ex('dips_chest',                'Dips (chest-leaning)',         'chest', 'bodyweight'),
  ex('svend_press',               'Svend Press',                  'chest', 'plate'),
  ex('landmine_press',            'Landmine Press',               'chest', 'barbell'),

  // === BACK ===
  ex('pullup',                    'Pullup',                       'back', 'bodyweight'),
  ex('chinup',                    'Chinup',                       'back', 'bodyweight'),
  ex('lat_pulldown',              'Lat Pulldown',                 'back', 'cable'),
  ex('lat_pulldown_close',        'Close-Grip Lat Pulldown',      'back', 'cable'),
  ex('seated_cable_row',          'Seated Cable Row',             'back', 'cable'),
  ex('barbell_row',               'Barbell Row',                  'back', 'barbell'),
  ex('pendlay_row',               'Pendlay Row',                  'back', 'barbell'),
  ex('dumbbell_row',              'Single-Arm Dumbbell Row',      'back', 'dumbbell'),
  ex('chest_supported_row',       'Chest-Supported Row',          'back', 'dumbbell'),
  ex('tbar_row',                  'T-Bar Row',                    'back', 'barbell'),
  ex('deadlift',                  'Conventional Deadlift',        'back', 'barbell'),
  ex('deadlift_sumo',             'Sumo Deadlift',                'back', 'barbell'),
  ex('rdl',                       'Romanian Deadlift',            'back', 'barbell'),
  ex('rack_pull',                 'Rack Pull',                    'back', 'barbell'),
  ex('shrug_barbell',             'Barbell Shrug',                'back', 'barbell'),
  ex('shrug_dumbbell',            'Dumbbell Shrug',               'back', 'dumbbell'),
  ex('face_pull',                 'Face Pull',                    'back', 'cable'),
  ex('inverted_row',              'Inverted Row',                 'back', 'bodyweight'),
  ex('hyperextension',            'Hyperextension',               'back', 'bodyweight'),
  ex('good_morning',              'Good Morning',                 'back', 'barbell'),

  // === SHOULDERS ===
  ex('ohp_barbell',               'Overhead Press (Barbell)',     'shoulders', 'barbell'),
  ex('ohp_dumbbell',              'Overhead Press (Dumbbell)',    'shoulders', 'dumbbell'),
  ex('arnold_press',              'Arnold Press',                 'shoulders', 'dumbbell'),
  ex('lateral_raise_dumbbell',    'Dumbbell Lateral Raise',       'shoulders', 'dumbbell'),
  ex('lateral_raise_cable',       'Cable Lateral Raise',          'shoulders', 'cable'),
  ex('front_raise_dumbbell',      'Dumbbell Front Raise',         'shoulders', 'dumbbell'),
  ex('front_raise_plate',         'Plate Front Raise',            'shoulders', 'plate'),
  ex('rear_delt_fly_dumbbell',    'Rear Delt Fly (Dumbbell)',     'shoulders', 'dumbbell'),
  ex('rear_delt_fly_machine',     'Rear Delt Fly (Machine)',      'shoulders', 'machine'),
  ex('upright_row',               'Upright Row',                  'shoulders', 'barbell'),
  ex('handstand_pushup',          'Handstand Pushup',             'shoulders', 'bodyweight'),
  ex('pike_pushup',               'Pike Pushup',                  'shoulders', 'bodyweight'),
  ex('cuban_press',               'Cuban Press',                  'shoulders', 'dumbbell'),

  // === BICEPS ===
  ex('barbell_curl',              'Barbell Curl',                 'biceps', 'barbell'),
  ex('ez_bar_curl',               'EZ-Bar Curl',                  'biceps', 'barbell'),
  ex('dumbbell_curl',             'Dumbbell Curl',                'biceps', 'dumbbell'),
  ex('hammer_curl',               'Hammer Curl',                  'biceps', 'dumbbell'),
  ex('preacher_curl',             'Preacher Curl',                'biceps', 'barbell'),
  ex('incline_dumbbell_curl',     'Incline Dumbbell Curl',        'biceps', 'dumbbell'),
  ex('concentration_curl',        'Concentration Curl',           'biceps', 'dumbbell'),
  ex('cable_curl',                'Cable Curl',                   'biceps', 'cable'),
  ex('cable_curl_rope',           'Rope Cable Curl',              'biceps', 'cable'),
  ex('spider_curl',               'Spider Curl',                  'biceps', 'dumbbell'),
  ex('zottman_curl',              'Zottman Curl',                 'biceps', 'dumbbell'),

  // === TRICEPS ===
  ex('tricep_pushdown_rope',      'Rope Tricep Pushdown',         'triceps', 'cable'),
  ex('tricep_pushdown_bar',       'Bar Tricep Pushdown',          'triceps', 'cable'),
  ex('overhead_tricep_extension', 'Overhead Tricep Extension',    'triceps', 'dumbbell'),
  ex('skullcrusher',              'Skullcrusher',                 'triceps', 'barbell'),
  ex('close_grip_bench',          'Close-Grip Bench Press',       'triceps', 'barbell'),
  ex('dips_triceps',              'Dips (triceps-leaning)',       'triceps', 'bodyweight'),
  ex('bench_dips',                'Bench Dips',                   'triceps', 'bodyweight'),
  ex('kickback_dumbbell',         'Tricep Kickback',              'triceps', 'dumbbell'),
  ex('jm_press',                  'JM Press',                     'triceps', 'barbell'),
  ex('diamond_pushup_tri',        'Diamond Pushup',               'triceps', 'bodyweight'),

  // === LEGS ===
  ex('back_squat',                'Back Squat',                   'legs', 'barbell'),
  ex('front_squat',               'Front Squat',                  'legs', 'barbell'),
  ex('goblet_squat',              'Goblet Squat',                 'legs', 'dumbbell'),
  ex('split_squat_bulgarian',     'Bulgarian Split Squat',        'legs', 'dumbbell'),
  ex('walking_lunge',             'Walking Lunge',                'legs', 'dumbbell'),
  ex('reverse_lunge',             'Reverse Lunge',                'legs', 'dumbbell'),
  ex('step_up',                   'Step-Up',                      'legs', 'dumbbell'),
  ex('leg_press',                 'Leg Press',                    'legs', 'machine'),
  ex('hack_squat',                'Hack Squat',                   'legs', 'machine'),
  ex('leg_extension',             'Leg Extension',                'legs', 'machine'),
  ex('leg_curl_seated',           'Seated Leg Curl',              'legs', 'machine'),
  ex('leg_curl_lying',            'Lying Leg Curl',               'legs', 'machine'),
  ex('nordic_curl',               'Nordic Curl',                  'legs', 'bodyweight'),
  ex('calf_raise_standing',       'Standing Calf Raise',          'legs', 'machine'),
  ex('calf_raise_seated',         'Seated Calf Raise',            'legs', 'machine'),
  ex('calf_raise_donkey',         'Donkey Calf Raise',            'legs', 'machine'),
  ex('pistol_squat',              'Pistol Squat',                 'legs', 'bodyweight'),
  ex('jump_squat',                'Jump Squat',                   'legs', 'bodyweight'),
  ex('box_jump',                  'Box Jump',                     'legs', 'bodyweight'),
  ex('wall_sit',                  'Wall Sit',                     'legs', 'bodyweight'),

  // === GLUTES ===
  ex('hip_thrust_barbell',        'Barbell Hip Thrust',           'glutes', 'barbell'),
  ex('glute_bridge',              'Glute Bridge',                 'glutes', 'bodyweight'),
  ex('cable_kickback',            'Cable Glute Kickback',         'glutes', 'cable'),
  ex('frog_pump',                 'Frog Pump',                    'glutes', 'bodyweight'),
  ex('curtsy_lunge',              'Curtsy Lunge',                 'glutes', 'dumbbell'),
  ex('single_leg_rdl',            'Single-Leg RDL',               'glutes', 'dumbbell'),
  ex('hip_abduction_machine',     'Hip Abduction Machine',        'glutes', 'machine'),

  // === CORE ===
  ex('plank',                     'Plank',                        'core', 'bodyweight'),
  ex('side_plank',                'Side Plank',                   'core', 'bodyweight'),
  ex('crunch',                    'Crunch',                       'core', 'bodyweight'),
  ex('situp',                     'Situp',                        'core', 'bodyweight'),
  ex('hanging_leg_raise',         'Hanging Leg Raise',            'core', 'bodyweight'),
  ex('hanging_knee_raise',        'Hanging Knee Raise',           'core', 'bodyweight'),
  ex('cable_crunch',              'Cable Crunch',                 'core', 'cable'),
  ex('russian_twist',             'Russian Twist',                'core', 'bodyweight'),
  ex('ab_wheel',                  'Ab Wheel Rollout',             'core', 'wheel'),
  ex('mountain_climber',          'Mountain Climber',             'core', 'bodyweight'),
  ex('bicycle_crunch',            'Bicycle Crunch',               'core', 'bodyweight'),
  ex('hollow_hold',               'Hollow Body Hold',             'core', 'bodyweight'),
  ex('dead_bug',                  'Dead Bug',                     'core', 'bodyweight'),
  ex('bird_dog',                  'Bird Dog',                     'core', 'bodyweight'),
  ex('flutter_kick',              'Flutter Kicks',                'core', 'bodyweight'),
  ex('v_up',                      'V-Up',                         'core', 'bodyweight'),
  ex('windshield_wiper',          'Windshield Wiper',             'core', 'bodyweight'),
  ex('plank_up_down',             'Plank Up-Down',                'core', 'bodyweight'),
  ex('toe_touch',                 'Toe Touch',                    'core', 'bodyweight'),
  ex('reverse_crunch',            'Reverse Crunch',               'core', 'bodyweight'),

  // === CARDIO ===
  ex('treadmill_run',             'Treadmill Run',                'cardio', 'machine'),
  ex('treadmill_walk',            'Treadmill Walk (incline)',     'cardio', 'machine'),
  ex('outdoor_run',               'Outdoor Run',                  'cardio', 'none'),
  ex('cycling_outdoor',           'Cycling (outdoor)',            'cardio', 'bike'),
  ex('cycling_stationary',        'Stationary Bike',              'cardio', 'machine'),
  ex('rowing_machine',            'Rowing Machine',               'cardio', 'machine'),
  ex('elliptical',                'Elliptical',                   'cardio', 'machine'),
  ex('stair_climber',             'Stair Climber',                'cardio', 'machine'),
  ex('jump_rope',                 'Jump Rope',                    'cardio', 'rope'),
  ex('burpee',                    'Burpee',                       'cardio', 'bodyweight'),
  ex('sprints',                   'Sprints',                      'cardio', 'none'),
  ex('swimming',                  'Swimming',                     'cardio', 'pool'),
  ex('hiit_circuit',              'HIIT Circuit',                 'cardio', 'bodyweight'),
  ex('battle_ropes',              'Battle Ropes',                 'cardio', 'ropes'),
  ex('sled_push',                 'Sled Push',                    'cardio', 'sled'),
  ex('farmers_walk',              'Farmer\'s Walk',               'cardio', 'dumbbell'),

  // === MOBILITY ===
  ex('couch_stretch',             'Couch Stretch',                'mobility', 'none'),
  ex('hip_flexor_stretch',        'Hip Flexor Stretch',           'mobility', 'none'),
  ex('pigeon_pose',               'Pigeon Pose',                  'mobility', 'none'),
  ex('downward_dog',              'Downward Dog',                 'mobility', 'none'),
  ex('cat_cow',                   'Cat-Cow',                      'mobility', 'none'),
  ex('thoracic_rotation',         'Thoracic Rotation',            'mobility', 'none'),
  ex('shoulder_dislocate',        'Shoulder Dislocate (band/PVC)','mobility', 'band'),
  ex('foam_roll_quads',           'Foam Roll Quads',              'mobility', 'roller'),
  ex('foam_roll_back',            'Foam Roll Back',               'mobility', 'roller'),
  ex('foam_roll_it_band',         'Foam Roll IT Band',            'mobility', 'roller'),
  ex('worlds_greatest_stretch',   'World\'s Greatest Stretch',    'mobility', 'none'),

  // === FULL BODY / OLYMPIC / COMPOUND ===
  ex('clean_and_jerk',            'Clean and Jerk',               'fullbody', 'barbell'),
  ex('snatch',                    'Snatch',                       'fullbody', 'barbell'),
  ex('power_clean',               'Power Clean',                  'fullbody', 'barbell'),
  ex('hang_clean',                'Hang Clean',                   'fullbody', 'barbell'),
  ex('thruster',                  'Thruster',                     'fullbody', 'barbell'),
  ex('kettlebell_swing',          'Kettlebell Swing',             'fullbody', 'kettlebell'),
  ex('turkish_getup',             'Turkish Get-Up',               'fullbody', 'kettlebell'),
  ex('man_maker',                 'Man Maker',                    'fullbody', 'dumbbell'),
  ex('clean_and_press',           'Clean and Press',              'fullbody', 'barbell'),
  ex('bear_crawl',                'Bear Crawl',                   'fullbody', 'bodyweight'),
];

export function getExercise(id) {
  return EXERCISES.find((e) => e.id === id);
}

export function exercisesByCategory(category) {
  return EXERCISES.filter((e) => e.category === category);
}
